services:
  mysql:
    image: mysql:8
    container_name: vspend-mysql
    environment:
      MYSQL_DATABASE: vspendtrack
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vspend-net

  backend:
    image: vspend-backend
    container_name: vspend-backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vspendtrack
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    networks:
      - vspend-net

  frontend:
    image: vspend-frontend
    container_name: vspend-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_SPRING_API_URL: http://vspendtrack-backend:8080
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - vspend-net
   prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - vspend-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - vspend-net

volumes:
  mysql_data:
  grafana-storage:

networks:
  vspend-net: