apiVersion: apps/v1
kind: Deployment
metadata:
  name: vspend-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vspend-backend
  template:
    metadata:
      labels:
        app: vspend-backend
    spec:
      containers:
        - name: backend
          image: varunvetrivendan/vspend-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/vspendtrack
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""  # Or change to use secret
