apiVersion: v1
kind: Service
metadata:
  name: vspendtrack-backend
spec:
  selector:
    app: vspendtrack-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
