apiVersion: apps/v1
kind: Deployment
metadata:
  name: vspend-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vspend-frontend
  template:
    metadata:
      labels:
        app: vspend-frontend
    spec:
      containers:
        - name: frontend
          image: varunvetrivendan/vspend-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: http://vspend-backend:8080
