apiVersion: v1
kind: Service
metadata:
  name: vspend-frontend
spec:
  selector:
    app: vspend-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Expose outside the cluster
