name: Backend CI

on:
  workflow_call: {}
  
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: vspendtrack
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build + Test with Maven (Debug Mode)
        run: |
          cd backend
          chmod +x mvnw || true
          ./mvnw clean install -X -Dspring.profiles.active=test
        env:
          MYSQL_URL: jdbc:mysql://localhost:3306/vspendtrack?useSSL=false&serverTimezone=UTC
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: ""  # ✅ Optional, empty string is fine
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
