name: Docker Release Frontend

on:
  push:
    tags:
      - frontend-v*

jobs:
  docker-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/frontend-v}" >> $GITHUB_ENV

      - name: Build and Tag Docker Image
        run: |
          docker build --build-arg VITE_SPRING_API_URL=http://vspend-backend:8080  -t ${{ secrets.DOCKER_USERNAME }}/vspend-frontend:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/vspend-frontend:latest ${{ secrets.DOCKER_USERNAME }}/vspend-frontend:${VERSION}

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/vspend-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/vspend-frontend:${VERSION}
