name: Docker Release Backend

on:
  push:
    tags:
      - backend-v*

jobs:
  docker-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/backend-v}" >> $GITHUB_ENV

      - name: Build and Tag Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vspend-backend:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/vspend-backend:latest ${{ secrets.DOCKER_USERNAME }}/vspend-backend:${VERSION}

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/vspend-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/vspend-backend:${VERSION}
