name: Release Please

on:
  push:
    branches:
      - main  # or 'master', whichever is your default branch

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: java  # since you're using Maven/Spring
