name: Unified Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  frontend:
    uses: ./.github/workflows/frontend.yml

  backend:
    uses: ./.github/workflows/backend.yml

  release:
    needs: [ frontend, backend ]
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}
          arguments: --ignore-commits-pattern="^Merge "
