name: Release Coordinator

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  frontend:
    uses: ./.github/workflows/frontend.yml

  backend:
    uses: ./.github/workflows/backend.yml

  release:
    name: Release Please
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
